# Generated by Django 2.2.7 on 2019-11-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoastBoast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.BooleanField(default=True)),
                ('content', models.CharField(max_length=280)),
                ('posttime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
