# Generated by Django 2.2.6 on 2019-11-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roastboast',
            old_name='type',
            new_name='roast',
        ),
    ]
