# Generated by Django 2.2.6 on 2019-11-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostpost', '0002_auto_20191125_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='roastboast',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roastboast',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
