# Generated by Django 3.0.1 on 2019-12-20 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_manufacturer_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='website',
            field=models.URLField(),
        ),
    ]
