# Generated by Django 3.0.1 on 2019-12-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0003_auto_20191220_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='size',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
